stages:
  - deploy
deployment:
  before_script:
    - "apk add --no-cache openssh"
    - "mkdir -p ~/.ssh"
    - "eval \"$(ssh-agent -s)\""
    - "echo \"$SSH_PRIVATE_KEY\" | tr -d '\\r' | ssh-add -"
    - "chmod 700 ~/.ssh"
    - ssh-keyscan -H "$client" >> ~/.ssh/known_hosts
    
  image: alpine
  only:
    - staging
    
  script:
    - pwd
    - ssh -o StrictHostKeyChecking=no ainova@"$client"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" set -f
    - ssh -o StrictHostKeyChecking=no ainova@"$client" sudo rm -rf /home/ainova/backendapp
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova && sudo git clone https://gitlab+deploy-token-2128250:F-YrbnQqsyHcy-FsCH2X@gitlab.com/Codistan/ai-nova/backend.git backendapp"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo git checkout staging"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" sudo chmod -R 777 /home/ainova/backendapp

    #.env configuration for pipeline
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'NODE_ENV=development' > .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'MONGODB_USERNAME=zeerasheed97' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'MONGODB_PASSWORD=ojCJIFub6SBiN16u' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'MONGODB_DATABASE_NAME=Nova' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'MONGODB_CLUSTER_ID=b7x4hpu' >> .env"
    
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'AWS_ACCESS_KEY_ID=AKIAXQAYYUPUEPZ7BAWI' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'AWS_SECRET_ACCESS_KEY=PWIVW29iM+TznmpbG5Kvq53df3LmMOrd9SV9D6XX' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'GOOGLE_CLIENT_ID=505612008126-vo4bejp0d82s959gkllpgoqbn0cd5pa2.apps.googleusercontent.com' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'S3_REGION=us-east-1' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'S3_BUCKET=ai-nova' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'EMAIL="harisbakhabarpk@gmail.com"' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'PASSWORD="cfivxreljrvzlqrt"' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'ACCESS_TOKEN_PRIVATE_KEY=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT2dJQkFBSkJBTlFLQStSV2ZQZFdHR25iYS9WRVo1TUs5cG1nMUlQay9paEE5dXF2Ny8rNVlzRjNUVURoCnFHZXN1bGJhdFFGdkNPaHVmSlNJQmFWT3RjbVZrTWZoWmRrQ0F3RUFBUUpBYkVlTkF6NnpaQzhBR3BhbGc4TmgKelBJdFNmaWFiWnd6dWVTcTh0L1RoRmQrUGhqN2IxTmphdjBMTjNGamhycjlzV3B2UjBBNW13OFpoSUFUNzZMUgpzUUloQU95Zmdhdy9BSTVoeGs3NmtWaVRRV0JNdjdBeERwdi9oSG1aUFdxclpyL1ZBaUVBNVdjalpmK0NaYlhTCnlpV3dUbEVENGVZQ3BSNk16Qk8wbFVhbExKdVRFL1VDSUhWTWZSUE9CNUNObDZqL1BaNFRJWTJEZm1MeGJyU1cKYmkxNWNhQzNaekFoQWlBNmUrVG1hQkdTWkp4c3ROY1I0RTJoRmNhdTJlOERTRExOcThrSWFsRkEwUUloQUlwUApUODFlWlNzYmVrNTlidGJPZ3J3bTJBdzJqUVk4TitJa3FMSTNySWFFCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'ACCESS_TOKEN_PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBTlFLQStSV2ZQZFdHR25iYS9WRVo1TUs5cG1nMUlQawovaWhBOXVxdjcvKzVZc0YzVFVEaHFHZXN1bGJhdFFGdkNPaHVmSlNJQmFWT3RjbVZrTWZoWmRrQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==' >> .env"
    
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'REFRESH_TOKEN_PRIVATE_KEY=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT2dJQkFBSkJBSnBBM08xOEZQRWtQR3lGZzUrS0xQUjJuSWFsQk1UeXo2bjJhdG1xQVNJZUFIMVBjeDRHCmZWV0pCWjRQUTBGTzlRYzBGYmxwMzB4UTl3WVpYSnBOVDdFQ0F3RUFBUUpBT1JwTDd1cGhRa2VjeXJ1K1Z5QXEKdGpEMmp1Mmx6MWJudzA2Q2phTmVtZ2NWMk9Fa25lbGplQTZOZGNGT3h6N0hRbTduRVVBbXJLV1JBM2htZ2hyNApRUUloQU96RmNGRmJuOUdoSzFrZ0RidWNqSFJYS2JEekcrQXBXbDlzTFVEZGJGMnBBaUVBcHNmWTZWdmJoTU5tCjlEcy9HRHNMZVhKaVVVWG9HNjUveldVQUJTRlpWc2tDSVFDcmFZMFUrWFpNdDVmQVlGcFExdGRBYXRIK0R5TEIKT0c3NjRrQW8wNlRlY1FJZ0gzb2ViVVNoOUxld2FhMzQ1WWpYVEkrVEVNWEIzZCtjVFZhZm4xaEE5VWtDSURNcApCMnVmMk85TDBENm1FbTBkSE5HZU5ITk9yMUhrRC9ZWjBWWFFESFgyCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'REFRESH_TOKEN_PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBSnBBM08xOEZQRWtQR3lGZzUrS0xQUjJuSWFsQk1UeQp6Nm4yYXRtcUFTSWVBSDFQY3g0R2ZWV0pCWjRQUTBGTzlRYzBGYmxwMzB4UTl3WVpYSnBOVDdFQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'EMAIL="harisbakhabarpk@gmail.com"' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo echo 'PASSWORD="cfivxreljrvzlqrt"' >> .env"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" sudo chmod 600 /home/ainova/backendapp/.env
    - ssh -o StrictHostKeyChecking=no ainova@"$client" sudo chown ainova:ainova /home/ainova/backendapp/.env
    #- ssh -o StrictHostKeyChecking=no ubuntu@"$client" "cd /home/ubuntu/thuckthay/backend-1 && sudo echo $'
    #  \n' > .env"
    #end of .env configurations
    - ssh -o StrictHostKeyChecking=no ainova@"$client" echo "Running npm install"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && source ~/.nvm/nvm.sh && nvm use 14"
    #- ssh -o StrictHostKeyChecking=no ubuntu@"$client" "cd /home/ubuntu/backendapp && sudo npm install && pm2 restart backendapp || pm2 start "npm start" --name=backendapp"
    
    - ssh -o StrictHostKeyChecking=no ainova@"$client" "cd /home/ainova/backendapp && sudo npm install && pm2 restart backendapp || pm2 start "npm start" --name backendapp"
    - ssh -o StrictHostKeyChecking=no ainova@"$client" sudo chmod -R 777 /home/ainova/backendapp
  stage: deploy